### ISSUE TITLE
Add French Top Servers

### ISSUE THREAD

**Issue by Metrakit** [exel80/EasyVote#6]
Hi,

I'm the owner of a french Top Servers for Rust. It's possible to add the API URLs of my french Top Servers in your plugin ? Or if its not possible, can I fork a copy to your plugin for make a plugin compatible for our french Top Servers ?

Thx in advance.

**Comment by exel80** [comment]
Can you link your website here and API docs.

**Comment by Metrakit** [comment]
Hey, thanks for your answer & sorry for the late.

So the website of my website is there : https://rust.top-serveurs.net and the documentation for the API is available there : https://api.top-serveurs.net/documentation.

I have checked fastly the source code of your library, then I think you can do that (with the URLs from my API) : 

```php
string[] TopServeurs = { "https://api.top-serveurs.net/votes?server_token={0}&steam_id={1}", "https://api.top-serveurs.net/votes/check?server_token={0}&steam_id={1}", "https://top-serveurs.net/srv/{0}" };
```

For vote the player should be connected on the server he is voting for (it's a security). If you need a test server, feel free to contact me or you can add a server on our Top Serveurs for do some tests :)

The API documentation is in french but all the HTTP errors are there. If you cant understand, feel free to contact me too :)

Big thanks to you !

Have a nice day.

**Comment by exel80** [comment]
Looks cool!
I tested out, and then publish it :)

**Comment by Metrakit** [comment]
Ok, thanks ! 😄

**Comment by Metrakit** [comment]
@exel80 Thanks for have added my Top Servers. I'm going to try it ! :)
